name: Deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          3.1.x
          6.0.x
          7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ./Float.FileDownloader/Float.FileDownloader.csproj -c Release /p:Version=${{ github.event.release.name }} /p:AssemblyVersion=${{ github.event.release.name }}
    - name: Pack
      run: dotnet pack --configuration Release --no-restore --no-build
    - name: Deploy to NuGet
      env:
        FLOAT_NUGET_TOKEN: ${{ secrets.FLOAT_NUGET_TOKEN }}
      run: dotnet nuget push ./Float.FileDownloader/bin/Release/Float.FileDownloader.${{ github.event.release.name }}.nupkg --api-key "${FLOAT_NUGET_TOKEN}" --source https://api.nuget.org/v3/index.json
